import { Component, OnInit } from '@angular/core';
import { ApiService } from '../services/api.service';
import { LoadingController } from '@ionic/angular';

@Component({
  selector: 'app-deal-tile',
  templateUrl: './deal-tile.component.html',
  styleUrls: ['./deal-tile.component.scss'],
})
export class DealTileComponent implements OnInit {

  circular: any[];
  content: string = 'Loading'
  data: any = {
    "errorcode": "0",
    "message": [
      {
        "oCouponShortDescription": "Oral-B 3D White Battery Power Electric Toothbrush",
        "CouponShortDescription": "Oral-B 3D White Battery Power Electric Toothbrush",
        "CouponLongDescription": "",
        "RewardType": "3",
        "RewardQty": "0",
        "Groupname": "",
        "oGroupname": "",
        "oDisplayPrice": "<sup>$</sup>6.24",
        "rewardGroupname": "",
        "Quantity": 0,
        "TotalQuantity": 0,
        "inCircular": 1,
        "RequiresActivation": "True",
        "IsMidWeek": 0,
        "FreeOffer": 0,
        "AltTitleBarImage": "",
        "LimitPerTransection": 0,
        "TileNumber": "1",
        "MemberID": 141134,
        "UPCRank": "701",
        "HasRelatedItems": 1,
        "OriginatorID": 0,
        "RelevantUPC": "6905583744",
        "IsEmployeeOffer": false,
        "BadgeId": "0",
        "RedeemLimit": 0,
        "RequiredQty": 1,
        "CategoryPriority": 18,
        "PercentSavings": "10.73",
        "FinalPrice": "6.2400",
        "AdPrice": "6.4900",
        "CouponDiscount": "0.00",
        "PersonalCircularID": 28618,
        "LoyaltyCardNumber": "9069048817",
        "PersonalCircularItemId": 1744681,
        "SectionNumber": 2,
        "StoreID": "168",
        "RegularPrice": "6.99",
        "DisplayPrice": "<sup>$</sup>6.24",
        "Savings": "0.7500",
        "DateAdded": "7/28/2020 11:50:03 PM",
        "ValidityStartDate": "7/29/20",
        "BadgeName": "",
        "BadgeFileName": "",
        "ValidityEndDate": "8/4/20",
        "Description": "Oral-B 3D White Battery Power Electric Toothbrush",
        "PackagingSize": "1 ct",
        "PricingMasterID": 0,
        "CategoryID": 10,
        "UPC": "6905583744",
        "CategoryName": "Health & Personal Care",
        "SmallImagePath": "https://images.immdemo.net/product/235/6905583744_2_e7196e43-e1eb-4e26-b2cb-d339d3477f7d.png",
        "LargeImagePath": "https://images.immdemo.net/product/235/6905583744_2_e7196e43-e1eb-4e26-b2cb-d339d3477f7d.png",
        "Isbadged": "False",
        "IsStacked": "0",
        "ListCount": 0,
        "SpecialInformation": "",
        "TileTemplateID": 3,
        "MinAmount": 0,
        "PriceAssociationCode": "",
        "PrimaryOfferTypeName": "Personal Deals",
        "OfferTypeTagName": "My Personal Deal",
        "OfferDefinition": "New Price",
        "CPRPromoTypeName": "Individual & Family UPC Offers",
        "RelevancyDetail": "Click Profile",
        "PrimaryOfferTypeId": 3,
        "OfferDetailId": 1,
        "OfferDefinitionId": 2,
        "CPRPromoTypeId": 1,
        "RelevancyTypeD": 2,
        "CouponID": 42789,
        "RelatedItemCount": 83,
        "ClickCount": 0,
        "PageID": 1,
        "BrandId": 1,
        "BrandName": "Sally Hansen",
        "DietaryId": 0,
        "DietaryName": "",
        "RewardValue": "6.24",
        "CouponImageURl": "http://images.immdemo.net/coupon/wlarge/couponImg.jpg",
        "OfferDayMsg": "",
        "OfferDay": "6",
        "RegularMsu": "1",
        "PosMultiple": "1",
        "IsFamily": "False"
      },
      {
        "oCouponShortDescription": "Entenmann's Snack Cakes Pies Or Brownies 6-8 ct ",
        "CouponShortDescription": "Entenmann's Snack Cakes Pies Or Brownies 6-8 ct ",
        "CouponLongDescription": "",
        "RewardType": "3",
        "RewardQty": "0",
        "Groupname": "",
        "oGroupname": "",
        "oDisplayPrice": "<sup>$</sup>2.35",
        "rewardGroupname": "",
        "Quantity": 0,
        "TotalQuantity": 0,
        "inCircular": 1,
        "RequiresActivation": "True",
        "IsMidWeek": 0,
        "FreeOffer": 0,
        "AltTitleBarImage": "",
        "LimitPerTransection": 0,
        "TileNumber": "2",
        "MemberID": 141134,
        "UPCRank": "701",
        "HasRelatedItems": 1,
        "OriginatorID": 0,
        "RelevantUPC": "7203002289",
        "IsEmployeeOffer": false,
        "BadgeId": "0",
        "RedeemLimit": 0,
        "RequiredQty": 1,
        "CategoryPriority": 9,
        "PercentSavings": "52.91",
        "FinalPrice": "2.3500",
        "AdPrice": "0.0000",
        "CouponDiscount": "0.00",
        "PersonalCircularID": 28618,
        "LoyaltyCardNumber": "9069048817",
        "PersonalCircularItemId": 1758211,
        "SectionNumber": 2,
        "StoreID": "168",
        "RegularPrice": "4.99",
        "DisplayPrice": "<sup>$</sup>2.35",
        "Savings": "2.6400",
        "DateAdded": "7/28/2020 11:50:03 PM",
        "ValidityStartDate": "7/29/20",
        "BadgeName": "",
        "BadgeFileName": "",
        "ValidityEndDate": "8/4/20",
        "Description": "Entenmann's Limited Edition Mini Snack Pies",
        "PackagingSize": "6 ct Box",
        "PricingMasterID": 0,
        "CategoryID": 16,
        "UPC": "7203002289",
        "CategoryName": "Snacks, Cookies & Candy",
        "SmallImagePath": "https://images.immdemo.net/product/235/7203002289_2_ebabfd40-0d8c-4c07-8211-a8ea121d7f0e.png",
        "LargeImagePath": "https://images.immdemo.net/product/235/7203002289_2_ebabfd40-0d8c-4c07-8211-a8ea121d7f0e.png",
        "Isbadged": "False",
        "IsStacked": "0",
        "ListCount": 0,
        "SpecialInformation": "",
        "TileTemplateID": 3,
        "MinAmount": 0,
        "PriceAssociationCode": "",
        "PrimaryOfferTypeName": "Personal Deals",
        "OfferTypeTagName": "My Personal Deal",
        "OfferDefinition": "New Price",
        "CPRPromoTypeName": "Individual & Family UPC Offers",
        "RelevancyDetail": "Click Profile",
        "PrimaryOfferTypeId": 3,
        "OfferDetailId": 1,
        "OfferDefinitionId": 2,
        "CPRPromoTypeId": 1,
        "RelevancyTypeD": 2,
        "CouponID": 42808,
        "RelatedItemCount": 29,
        "ClickCount": 0,
        "PageID": 1,
        "BrandId": 1,
        "BrandName": "Sally Hansen",
        "DietaryId": 0,
        "DietaryName": "",
        "RewardValue": "2.35",
        "CouponImageURl": "http://images.immdemo.net/coupon/wlarge/couponImg.jpg",
        "OfferDayMsg": "",
        "OfferDay": "6",
        "RegularMsu": "0",
        "PosMultiple": "0",
        "IsFamily": "True"
      },
      {
        "oCouponShortDescription": "Sabra Hummus 10 oz ",
        "CouponShortDescription": "Sabra Hummus 10 oz ",
        "CouponLongDescription": "",
        "RewardType": "3",
        "RewardQty": "0",
        "Groupname": "",
        "oGroupname": "",
        "oDisplayPrice": "<sup>$</sup>2.69",
        "rewardGroupname": "",
        "Quantity": 0,
        "TotalQuantity": 0,
        "inCircular": 1,
        "RequiresActivation": "True",
        "IsMidWeek": 0,
        "FreeOffer": 0,
        "AltTitleBarImage": "",
        "LimitPerTransection": 0,
        "TileNumber": "3",
        "MemberID": 141134,
        "UPCRank": "0",
        "HasRelatedItems": 1,
        "OriginatorID": 0,
        "RelevantUPC": "4082201114",
        "IsEmployeeOffer": false,
        "BadgeId": "0",
        "RedeemLimit": 0,
        "RequiredQty": 1,
        "CategoryPriority": 9,
        "PercentSavings": "18.24",
        "FinalPrice": "2.6900",
        "AdPrice": "2.9800",
        "CouponDiscount": "0.00",
        "PersonalCircularID": 28618,
        "LoyaltyCardNumber": "9069048817",
        "PersonalCircularItemId": 1758299,
        "SectionNumber": 3,
        "StoreID": "168",
        "RegularPrice": "3.29",
        "DisplayPrice": "<sup>$</sup>2.69",
        "Savings": "0.6000",
        "DateAdded": "7/28/2020 11:50:03 PM",
        "ValidityStartDate": "7/29/20",
        "BadgeName": "",
        "BadgeFileName": "",
        "ValidityEndDate": "8/4/20",
        "Description": "Sabra Classic Hummus",
        "PackagingSize": "10 oz Tub",
        "PricingMasterID": 0,
        "CategoryID": 16,
        "UPC": "4082201114",
        "CategoryName": "Snacks, Cookies & Candy",
        "SmallImagePath": "https://images.immdemo.net/product/235/4082201114_2_0fb57c96-c9c4-4a09-9a5b-3afcf2384e5a.png",
        "LargeImagePath": "https://images.immdemo.net/product/235/4082201114_2_0fb57c96-c9c4-4a09-9a5b-3afcf2384e5a.png",
        "Isbadged": "False",
        "IsStacked": "0",
        "ListCount": 0,
        "SpecialInformation": "",
        "TileTemplateID": 3,
        "MinAmount": 0,
        "PriceAssociationCode": "",
        "PrimaryOfferTypeName": "Personal Deals",
        "OfferTypeTagName": "My Personal Deal",
        "OfferDefinition": "New Price",
        "CPRPromoTypeName": "Individual & Family UPC Offers",
        "RelevancyDetail": "Pushed",
        "PrimaryOfferTypeId": 3,
        "OfferDetailId": 1,
        "OfferDefinitionId": 2,
        "CPRPromoTypeId": 1,
        "RelevancyTypeD": 5,
        "CouponID": 42856,
        "RelatedItemCount": 2645,
        "ClickCount": 0,
        "PageID": 1,
        "BrandId": 1,
        "BrandName": "Sally Hansen",
        "DietaryId": 0,
        "DietaryName": "",
        "RewardValue": "2.69",
        "CouponImageURl": "http://images.immdemo.net/coupon/wlarge/couponImg.jpg",
        "OfferDayMsg": "",
        "OfferDay": "6",
        "RegularMsu": "1",
        "PosMultiple": "1",
        "IsFamily": "True"
      },
      {
        "oCouponShortDescription": "Nabisco Snack Crackers 3.5-9.1 oz ",
        "CouponShortDescription": "Nabisco Snack Crackers 3.5-9.1 oz ",
        "CouponLongDescription": "",
        "RewardType": "3",
        "RewardQty": "0",
        "Groupname": "",
        "oGroupname": "",
        "oDisplayPrice": "<sup>$</sup>2.84",
        "rewardGroupname": "",
        "Quantity": 0,
        "TotalQuantity": 0,
        "inCircular": 1,
        "RequiresActivation": "True",
        "IsMidWeek": 0,
        "FreeOffer": 0,
        "AltTitleBarImage": "",
        "LimitPerTransection": 0,
        "TileNumber": "4",
        "MemberID": 141134,
        "UPCRank": "0",
        "HasRelatedItems": 1,
        "OriginatorID": 0,
        "RelevantUPC": "4400000224",
        "IsEmployeeOffer": false,
        "BadgeId": "0",
        "RedeemLimit": 0,
        "RequiredQty": 1,
        "CategoryPriority": 9,
        "PercentSavings": "18.62",
        "FinalPrice": "2.8400",
        "AdPrice": "2.9900",
        "CouponDiscount": "0.00",
        "PersonalCircularID": 28618,
        "LoyaltyCardNumber": "9069048817",
        "PersonalCircularItemId": 1745779,
        "SectionNumber": 3,
        "StoreID": "168",
        "RegularPrice": "3.49",
        "DisplayPrice": "<sup>$</sup>2.84",
        "Savings": "0.6500",
        "DateAdded": "7/28/2020 11:50:03 PM",
        "ValidityStartDate": "7/29/20",
        "BadgeName": "",
        "BadgeFileName": "",
        "ValidityEndDate": "8/4/20",
        "Description": "Nabisco Vegetable Thins",
        "PackagingSize": "8 oz Box",
        "PricingMasterID": 0,
        "CategoryID": 16,
        "UPC": "4400000224",
        "CategoryName": "Snacks, Cookies & Candy",
        "SmallImagePath": "https://images.immdemo.net/product/235/4400000224_2_e58b02e6-471f-47ea-b83a-59b0478b0dce.png",
        "LargeImagePath": "https://images.immdemo.net/product/235/4400000224_2_e58b02e6-471f-47ea-b83a-59b0478b0dce.png",
        "Isbadged": "False",
        "IsStacked": "0",
        "ListCount": 0,
        "SpecialInformation": "",
        "TileTemplateID": 3,
        "MinAmount": 0,
        "PriceAssociationCode": "",
        "PrimaryOfferTypeName": "Personal Deals",
        "OfferTypeTagName": "My Personal Deal",
        "OfferDefinition": "New Price",
        "CPRPromoTypeName": "Individual & Family UPC Offers",
        "RelevancyDetail": "Pushed",
        "PrimaryOfferTypeId": 3,
        "OfferDetailId": 1,
        "OfferDefinitionId": 2,
        "CPRPromoTypeId": 1,
        "RelevancyTypeD": 5,
        "CouponID": 42820,
        "RelatedItemCount": 24104,
        "ClickCount": 0,
        "PageID": 1,
        "BrandId": 1,
        "BrandName": "Sally Hansen",
        "DietaryId": 0,
        "DietaryName": "",
        "RewardValue": "2.84",
        "CouponImageURl": "http://images.immdemo.net/coupon/wlarge/couponImg.jpg",
        "OfferDayMsg": "",
        "OfferDay": "6",
        "RegularMsu": "1",
        "PosMultiple": "1",
        "IsFamily": "True"
      }
    ]
  }

  constructor(
    private loadingController: LoadingController,
    private apiService: ApiService) {

  }

  ngOnInit() {
    this.detailsfetch();
    //this.circular = this.data['message'];
    //this.apiService.getCircular().subscribe((data) => {
    //this.circular = data['message'];
      //console.log("News " + JSON.stringify(data));
    //})
  }

  async detailsfetch() {
    const loading = await this.loadingController.create({
      message : 'Please wait',
      translucent : true,
    });
    await loading.present();
    this.apiService.getCircular().subscribe((data) => {
      this.circular = data['message'];
      loading.dismiss();
    })
    }
}
